### ISSUE TITLE
Rename "uses_south" setting

### ISSUE THREAD

**Issue by ekoval** [yola/yodeploy#161]
One of our applications uses Django 1.8 now, which has native support of migrations, we don't use `South` there. However, we still have to use `uses_south = True` setting in WLProxy deploy hooks, because otherwise migrations won't be run on deploy (https://github.com/yola/yodeploy/blob/23ca59d1358c8f0bc8b97423d518b3656d7c91bd/yodeploy/hooks/django.py#L112)

I think we can think how to rename this setting to something more neutral, not related to South.

**Comment by stefanor** [comment]
`has_migrations` ?

**Comment by ekoval** [comment]
Sounds good to me. Thanks.
