### ISSUE TITLE
Indicate that yodeploy didn't deploy a new version

### ISSUE THREAD

**Issue by adrianmoisey** [yola/yodeploy#168]
We've got :boom: showing when we deploy to production, what about something to indicate that the version didn't change?

**Comment by adrianmoisey** [comment]
How about :repeat: ?

**Comment by AceFire6** [comment]
What about :repeat_one: ?

**Comment by alexmojaki** [comment]
Is there any relation between whether the :repeat: should show and whether it's in production? That is, should it still show :repeat: for QA, and can it show :repeat: and :boom: at the same time?

**Comment by AceFire6** [comment]
Ohh, I didn't even thing about that. I'll change it based on any further clarification.

**Comment by adrianmoisey** [comment]
> Is there any relation between whether the :repeat: should show and whether it's in production? That is, should it still show :repeat: for QA, and can it show :repeat: and :boom: at the same time?

I think so, yes.

```
emoji = ''
if current_version == new_version:
    emoji += ':repeat: '
if env == production:
    emoji += ':boom: '
```
