### ISSUE TITLE
yodeploy didn't get tagged for versions 0.7.0 and 0.7.1

### ISSUE THREAD

**Issue by jamesodo** [yola/yodeploy#169]
@adrianmoisey, if we tag them now, will the auto upload to yolapi break since they are already there?
If the auto upload fails, is that something that can be ignored since they are already there?

**Comment by adrianmoisey** [comment]
I'll disable the jenkins job, tag them, then reenable the jenkins job.

**Comment by adrianmoisey** [comment]
> I'll disable the jenkins job

Just to discover that yodeploy doesn't have an upload job. Whoops!
I've pushed the tags, I'll make an upload job shortly.
