### ISSUE TITLE
LockFile race condition

### ISSUE THREAD

**Issue by thomasw** [yola/yodeploy#176]
There appears to be a race condition in yodeploy.locking.LockFile (and its subclass, SpinLockFile). You should be able to see this manifest itself as intermittent failures in the test suite:

```
nosetests yodeploy.tests.test_locking:SpinLockFileTest.test_retries
```

This will occasionally result in test failures with output similar to the following:

```
(yodeploy-2.7.3)thomas@radiant:~/Sites/yodeploy[master]$ nosetests yodeploy.tests.test_locking:SpinLockFileTest.test_retries
/Users/thomas/.pyenv/versions/2.7.3/envs/yodeploy-2.7.3/lib/python2.7/site-packages/nose/plugins/manager.py:395: RuntimeWarning: Unable to load plugin specselector = spec.cli:CustomSelector: (nose 1.2.1 (/Users/thomas/.pyenv/versions/2.7.3/envs/yodeploy-2.7.3/lib/python2.7/site-packages), Requirement.parse('nose>=1.3'))
  RuntimeWarning)

Spin lock file
- retries

----------------------------------------------------------------------
Ran 1 test in 0.210s

OK

(yodeploy-2.7.3)thomas@radiant:~/Sites/yodeploy[master]$ nosetests yodeploy.tests.test_locking:SpinLockFileTest.test_retries
/Users/thomas/.pyenv/versions/2.7.3/envs/yodeploy-2.7.3/lib/python2.7/site-packages/nose/plugins/manager.py:395: RuntimeWarning: Unable to load plugin specselector = spec.cli:CustomSelector: (nose 1.2.1 (/Users/thomas/.pyenv/versions/2.7.3/envs/yodeploy-2.7.3/lib/python2.7/site-packages), Requirement.parse('nose>=1.3'))
  RuntimeWarning)

Spin lock file
- retries

----------------------------------------------------------------------
Ran 1 test in 0.205s

OK

(yodeploy-2.7.3)thomas@radiant:~/Sites/yodeploy[master]$ nosetests yodeploy.tests.test_locking:SpinLockFileTest.test_retries
/Users/thomas/.pyenv/versions/2.7.3/envs/yodeploy-2.7.3/lib/python2.7/site-packages/nose/plugins/manager.py:395: RuntimeWarning: Unable to load plugin specselector = spec.cli:CustomSelector: (nose 1.2.1 (/Users/thomas/.pyenv/versions/2.7.3/envs/yodeploy-2.7.3/lib/python2.7/site-packages), Requirement.parse('nose>=1.3'))
  RuntimeWarning)

Spin lock file
- retries (FAILED)

======================================================================
FAIL: test_retries (yodeploy.tests.test_locking.SpinLockFileTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/thomas/Sites/yodeploy/yodeploy/tests/test_locking.py", line 73, in test_retries
    self.assertFalse(lf.held)
AssertionError: True is not false
-------------------- >> begin captured logging << --------------------
yodeploy.locking: DEBUG: Lock unavialible, retrying for 0 seconds...
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 0.209s

FAILED (failures=1)
```

I haven't looked into it much, but I believe the problem is in the following block https://github.com/yola/yodeploy/blob/0c0f9eddd268ba2fc43c24f982bbcfacd784fe24/yodeploy/locking.py#L34-L40. Since the two `os.open` operations are not atomic, there is an opening for the lock file to be deleted in between the two open attempts:

1. Process 1 creates a lock.
2. Process 2 attempts to create the same lock, but fails because the lock file already exists. It raises an exception, and moves on to the except block.
3. Process 1 releases and deletes the lock.
4. Process 2 attempts to open the lock because its create attempt failed, but the file no longer exists. An exception is raised.

**Comment by stefanor** [comment]
> Since the two os.open operations are not atomic

The first one is atomic, because we're using O_EXCL.

I think the issue is that the second one is assigning `self._f`, which makes `held` True, even if the lock isn't held. There is a similar race in `release()` where `self._f` is still assigned a value, and so `held` is True, after we've released the lock.

**Comment by stefanor** [comment]
To reproduce it, I have to remove [the sleep](https://github.com/yola/yodeploy/blob/0c0f9eddd268ba2fc43c24f982bbcfacd784fe24/yodeploy/locking.py#L84)
