### ISSUE TITLE
Do not break on symlink creation in case it exists.

### ISSUE THREAD

**Issue by RayeN** [yola/yodeploy#203]
Our local-deploy-bootstrap doesn't handle the case when the following  symlink is already created: https://github.com/yola/yodeploy/blob/master/scripts/local-deploy-bootstrap.py#L455-L457

**Comment by stefanor** [comment]
That block is inside ` if not os.path.exists(deploy_settings_fn):` so I don't know how that could happen.

**Comment by RayeN** [comment]
But it happened at least twice (with both Ivan and Mykhailo, MacOS and Ubuntu).  Maybe it could happen because of 
```Returns False for broken symbolic links. On some platforms, this function may return False if permission is not granted to execute os.stat() on the requested file, even if the path physically exists.```

**Comment by stefanor** [comment]
Ah, yes, that's it.
