### ISSUE TITLE
Connecting to a bucket with dots fails ssl validation

### ISSUE THREAD

**Issue by stormf** [yola/yodeploy#205]
There's a long thread about this at https://github.com/boto/boto/issues/2836 and we seem to have attempted to fix it in https://github.com/yola/yodeploy/pull/186/commits/ba4f0e37e2ce2a560a9e133eafebd3a27df10a37 but attempting to deploy on xenial with yodeploy 0.8.4 fails with
```
ssl.CertificateError: hostname 'yola.deploy-artifacts.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com'
```

**Comment by stefanor** [comment]
Nope, lintereview is not using yodeploy 0.8.4, it's using 0.4.17: https://github.com/yola/lintreview/blob/master/deploy/requirements.txt

It needs to be bumped, see: yola/production#3817
