### ISSUE TITLE
Wrong shebang in scripts in virtualenv/bin directory

### ISSUE THREAD

**Issue by kosmos342** [yola/yodeploy#208]
`celery` for `importer`(`/srv/importer/live/virtualenv/bin/celery`) has strange shebang:
```
#!/var/lib/jenkins/workspace/Build-importer/virtualenv/bin/python
```
expected:
```
##!/usr/bin/env python3.5
```

`importer` project uses Python 3.5. Same problem with `importservice`(python 3.5.2 also)

Looks like problem here:
https://github.com/yola/yodeploy/blob/7ec27f895aee3a5d3ecc4efd55c19b7a111b2b5b/yodeploy/virtualenv.py#L174-L176

**Comment by stefanor** [comment]
Yeah, this is a long known issue. Lazy answer: don't rely on the shebangs. You can't put relative paths in shebangs, and so we can't really do much better.

**Comment by blaix** [comment]
> we can't really do much better.

does that mean this should be closed?

**Comment by stefanor** [comment]
Yeah, it's WONTFIX territory.
