### ISSUE TITLE
SSLError  "bad handshake: SysCallError(104, 'ECONNRESET')"

### ISSUE THREAD

**Issue by VolVoz** [yola/yodeploy#213]
During deploy applications from fieldhq on:
-  `sb5.prod.inet.yola.net`
-  `sb6.prod.inet.yola.net`
-  `sb4.prod.inet.yola.net` 

we got an error:

https://sentry.io/yola/fieldhq/issues/443250339/

looks like need to check the libraries version

**Comment by snitch** [comment]
@VolVoz: This issue is now a priority.

**Comment by VolVoz** [comment]
I've investigated this issue and I sent requests to get an answer from the `yodeploy-server`. What I got:
1. sending curl GET request from `serv.infra2.prod.inet.yola.net` -> `serv1.prod.inet.yola.net`, the same as in other sunny nodes here https://github.com/yola/production/issues/4405: 
works well :+1: 
2. sending curl GET request from `serv.infra2.prod.inet.yola.net` -> `sb*.prod.inet.yola.net`
```
volvoz@serv:~$ curl -v -X GET -U fieldhq:Imaiwiech3mahx1xaiza https://sb4.prod.inet.yola.net:10000/deploy/sbbe
* About to connect() to sb4.prod.inet.yola.net port 10000 (#0)
*   Trying 208.75.209.72... connected
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* Unknown SSL protocol error in connection to sb4.prod.inet.yola.net:10000 
* Closing connection #0
curl: (35) Unknown SSL protocol error in connection to sb4.prod.inet.yola.net:10000 
```
 - versions of ssl packages are the same
 - @fr33l has idea that it can be related to Ubuntu version, I've made env with v12.04 `boom.env.yola.net` and everything works well for him

@yola/operations-engineering , do you have any ideas wherever we can check it?

**Comment by VolVoz** [comment]
moved
