### ISSUE TITLE
Django hooks for nginx hosted apps

### ISSUE THREAD

**Issue by serhii-karelov** [yola/yodeploy#218]
We have Django apps which are run behind nginx (`ws-service`). The problem is that [`hooks.django.DjangoApp`](https://github.com/yola/yodeploy/blob/319f07df1c0e894c80ce5b32f52f1718eeabaae7/yodeploy/hooks/django.py#L17) cannot be used with `ws-service` because it works only with Apache hosted apps. 

We need `DjangoApp` mixin which is webserver agnostic.

I believe that replacing `ApacheHostedApp` with `ConfiguratedApp` in `DjangoApp` class parents will work for us, but I may not be aware about some pitfalls. 

@yola/service-engineering  @yola/operations-engineering

**Comment by stefanor** [comment]
IIRC this was done, in #219.
